### ISSUE TITLE
Cannot compile sample code

### ISSUE THREAD

**Issue by kneetate** [Makeblock-official/CyberPi-Library-for-Arduino#1]
I want to write mbot2 programs in the Arduino IDE.
I tried to compile music.ino in examples, but compile error occurs.

`fatal error: FreeRTOS.h: No such file or directory
 #include "FreeRTOS.h"
          ^~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board ESP32 Dev Module.`
fatal error: FreeRTOS.h: No such file or directory
 #include "FreeRTOS.h"
          ^~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board ESP32 Dev Module.`

Help me please.

**Comment by xeecos** [comment]
fixed
remove the line #include "FreeRTOS.h"
